### ISSUE TITLE
Error: Spawn

### ISSUE THREAD

**Issue by aviadhahami** [mewben/go-react-project#1]
Hi,
we're encountering this when trying to initialize your repo. Any idea?

![image](https://cloud.githubusercontent.com/assets/7353632/15070780/4f199144-138f-11e6-818e-9190fd7aab19.png)

**Comment by Bonzyng** [comment]
+1

**Comment by mrsufgi** [comment]
+1 !

**Comment by mewben** [comment]
@aviadhahami @Bonzyng @mrsufgi Do you mind posting your node version? I tested this with Node v4.4.4 LTS... and it is working fine..

**Comment by mewben** [comment]
Closing this as I received no response.. Please reopen if still not fixed.
